# Generated by Django 4.2.5 on 2023-10-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='satff',
            new_name='staff',
        ),
    ]
