# Generated by Django 4.2.5 on 2023-10-09 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_order_reporting_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnover_rate', models.FloatField(null=True)),
                ('holding_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('obsolescence_risks', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
            options={
                'verbose_name_plural': 'Inventory Metrics',
            },
        ),
    ]
