# Generated by Django 4.2.5 on 2023-10-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_order_order_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='cost_per_unit',
        ),
    ]
