# Generated by Django 4.2.5 on 2023-10-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_cost_product_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cogs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='holding_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
