# Generated by Django 4.2.5 on 2023-10-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_product_obs_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymetrics',
            name='holding_cost',
        ),
        migrations.RemoveField(
            model_name='inventorymetrics',
            name='obsolescence_risks',
        ),
    ]
