# Generated by Django 4.2.5 on 2023-10-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
