# Generated by Django 4.2.5 on 2023-11-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_order_delivery_date_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='market_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
